// Automatically generated by makemoduledefs.py.

#if (1)
    extern const struct _mp_obj_module_t ad717x_type;
    #define MODULE_DEF_MP_QSTR_AD717X { MP_ROM_QSTR(MP_QSTR_ad717x), MP_ROM_PTR(&ad717x_type) },
#else
    #define MODULE_DEF_MP_QSTR_AD717X
#endif

#if (1)
    extern const struct _mp_obj_module_t mycounter_type;
    #define MODULE_DEF_MP_QSTR_COUNTER { MP_ROM_QSTR(MP_QSTR_counter), MP_ROM_PTR(&mycounter_type) },
#else
    #define MODULE_DEF_MP_QSTR_COUNTER
#endif

#if (1)
    extern const struct _mp_obj_module_t dmath_cmodule;
    #define MODULE_DEF_MP_QSTR_DMATH { MP_ROM_QSTR(MP_QSTR_dmath), MP_ROM_PTR(&dmath_cmodule) },
#else
    #define MODULE_DEF_MP_QSTR_DMATH
#endif

#if (1)
    extern const struct _mp_obj_module_t myfreq_type;
    #define MODULE_DEF_MP_QSTR_FREQ { MP_ROM_QSTR(MP_QSTR_freq), MP_ROM_PTR(&myfreq_type) },
#else
    #define MODULE_DEF_MP_QSTR_FREQ
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_uarray;
    #define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },
#else
    #define MODULE_DEF_MP_QSTR_UARRAY
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_AD717X \
    MODULE_DEF_MP_QSTR_COUNTER \
    MODULE_DEF_MP_QSTR_DMATH \
    MODULE_DEF_MP_QSTR_FREQ \
    MODULE_DEF_MP_QSTR_UARRAY \
// MICROPY_REGISTERED_MODULES
